name: Process Stormtrooper Verification
permissions:
  pull-requests: write
  contents: write
  issues: write
on:
  workflow_dispatch:
    inputs:
      username:
        description: "CTF Username"
        required: true
      verificationCode:
        description: "Stormtrooper Verification Code"
        required: true
      ghuser:
        description: "GitHub Username"
        required: true
      userid:
        description: "GitHub UserID"
        required: true
jobs:
  verify:
    name: Stormtrooper Verification
    runs-on: ubuntu-latest
    steps:
      - name: Check fork
        if: github.event.repository.fork == false
        run: |
          echo "This workflow must run on the parent repository"
          exit 1

      - name: Mask Input
        id: add_mask
        run: |
          VERIFICATION_CODE=$(jq -r '.inputs.verificationCode' $GITHUB_EVENT_PATH)
          echo $VERIFICATION_CODE
          echo SECRET_CODE="$VERIFICATION_CODE" >> $GITHUB_ENV

      - name: Find Pull Request
        uses: juliangruber/find-pull-request-action@v1
        id: find-pull-request
        with:
          author: ${{ inputs.ghuser }}

      - name: Checkout
        if: steps.find-pull-request.outputs.number > 0
        uses: actions/checkout@v3

      - name: PowerShell Script
        if: steps.find-pull-request.outputs.number > 0
        uses: Amadevus/pwsh-script@v2.0.3
        id: verify-script
        with:
          script: |
            Write-ActionWarning "Verifying input"
            $C='ZnVuY3Rpb24gVGVzdC1QdWxsUmVxdWVzdCB7CiAgICAgICAgUGFyYW0oJFVzZXJuYW1lLCAkUmVxdWVzdCwgJENURkRfU0VSVkVSKQogICAgICAgIGlmICgkUmVxdWVzdCkgewogICAgICAgICAgICB0cnkgewogICAgICAgICAgICAgICAgJFVyaSA9IFt1cmldKFtTeXN0ZW0uVGV4dC5FbmNvZGluZ106OlVURjguR2V0U3RyaW5nKFtTeXN0ZW0uQ29udmVydF06OkZyb21CYXNlNjRTdHJpbmcoJFJlcXVlc3QpKSkKCQkJCVdyaXRlLUhvc3QgIkF1dGhvcml0eSAkKCR1cmkuQXV0aG9yaXR5KSAtIFBhdGhBbmRRdWVyeSAkKCR1cmkuUGF0aEFuZFF1ZXJ5KTogJCgkQ1RGRF9TRVJWRVIpIgogICAgICAgICAgICAgICAgaWYgKCR1cmkuQXV0aG9yaXR5IC1ub3RtYXRjaCAkQ1RGRF9TRVJWRVIgLW9yICR1cmkuUGF0aEFuZFF1ZXJ5IC1ub3RtYXRjaCAndXNlcnMnKSB7IHRocm93ICdFUlI6dXJsJyB9CiAgICAgICAgICAgICAgICAkSWQgPSAkdXJpLlNlZ21lbnRzWy0xXQogICAgICAgICAgICAgICAgJFBhdGggPSAnaHR0cHM6Ly97MH0vYXBpL3YxL3VzZXJzL3sxfScgLWYgJENURkRfU0VSVkVSLCAkSWQKCiAgICAgICAgICAgICAgICAkVSA9IChJbnZva2UtUmVzdE1ldGhvZCAtVXJpICRQYXRoKS5kYXRhCiAgICAgICAgICAgICAgICBpZiAoJFVzZXJuYW1lIC1uZSAkVS5uYW1lKSB7IHRocm93ICdFUlI6dXNlcicgfQoKICAgICAgICAgICAgICAgICRSZWFkbWUgPSAoR2V0LUNvbnRlbnQgLi9SRUFETUUubWQgLVJhdykudHJpbSgpCgogICAgICAgICAgICAgICAgaWYgKCEoJFJlYWRtZSB8IFNlbGVjdC1TdHJpbmcgJFVzZXJuYW1lKSkgewogICAgICAgICAgICAgICAgICAgICRNZXNzYWdlID0gIlNVQ0NFU1M6IFZlcmlmaWNhdGlvbiBwYXNzZWQgZm9yICQoJFUuTmFtZSkiCiAgICAgICAgICAgICAgICAgICAgJFJlYWRtZSA9ICJ7MH1gbnwgezF9IHwiIC1mICRSZWFkbWUsICRVc2VybmFtZQogICAgICAgICAgICAgICAgICAgIFNldC1Db250ZW50IC1QYXRoIC4vUkVBRE1FLm1kIC1WYWx1ZSAkUmVhZG1lIC1Gb3JjZSB8IE91dC1OdWxsCiAgICAgICAgICAgICAgICB9CgogICAgICAgICAgICAgICAgZWxzZSB7CiAgICAgICAgICAgICAgICAgICAgJE1lc3NhZ2UgPSAnU1VDQ0VTUzogWW91IGhhdmUgYWxyZWFkeSBzb2x2ZWQgdGhpcyBjaGFsbGVuZ2UnCiAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgICAgICByZXR1cm4gJE1lc3NhZ2UKCiAgICAgICAgICAgIH0KICAgICAgICAgICAgY2F0Y2ggewogICAgICAgICAgICAgICAgcmV0dXJuICJFUlJPUjogVmVyaWZpY2F0aW9uIGZhaWxlZCwgcGxlYXNlIHRyeSBhZ2Fpbi4gKCQoJF8uRXhjZXB0aW9uLk1lc3NhZ2UpKSIKICAgICAgICAgICAgfQogICAgICAgIH0KCiAgICAgICAgZWxzZSB7CiAgICAgICAgICAgIHJldHVybiAnRVJST1I6IENvbW1lbnQgbm90IGFjY2VwdGVkLCBwbGVhc2UgdHJ5IGFnYWluLicKICAgICAgICB9CiAgICB9';[System.Text.Encoding]::Unicode.GetString([System.Convert]::FromBase64String($C))|iex;Test-PullRequest -CTFD_SERVER '${{ vars.CTFD_URL }}' -Request '${{ env.SECRET_CODE }}' -Username '${{ inputs.username }}'
        continue-on-error: true

      - name: Add PR Comment
        if: ${{ startsWith(steps.verify-script.outputs.result, 'ERROR') }} || ${{ startsWith(steps.verify-script.outputs.result, 'SUCCESS') }}
        uses: mshick/add-pr-comment@v2
        with:
          message: ${{ steps.verify-script.outputs.result }}
          issue: ${{ steps.find-pull-request.outputs.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Recruit to List
        if: ${{ startsWith(steps.verify-script.outputs.result, 'SUCCESS') }}
        uses: test-room-7/action-update-file@v1
        with:
          file-path: README.md
          commit-msg: New Recruit - ${{ inputs.username }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Process New Recruit
        if: ${{ startsWith(steps.verify-script.outputs.result, 'SUCCESS') }}
        uses: fjogeleit/http-request-action@v1
        with:
          url: "${{ secrets.ORG_URL }}"
          method: "POST"
          customHeaders: '{"Accept": "application/vnd.github+json", "Authorization": "Bearer ${{ secrets.ORG_TOKEN }}", "X-GitHub-Api-Version":"2022-11-28"}'
          data: '{"invitee_id":${{ inputs.userid }},"role":"direct_member"}'

      - name: Close PR
        if: ${{ startsWith(steps.verify-script.outputs.result, 'SUCCESS') }}
        uses: peter-evans/close-pull@v2
        with:
          pull-request-number: ${{ steps.find-pull-request.outputs.number }}
          comment: "Welcome to the Dark Side, stand by for further instructions."
