name: Process Stormtrooper Verification
permissions:
  pull-requests: write
  contents: write
  issues: write
on:
  workflow_dispatch:
    inputs:
      username:
        description: "CTF Username"
        required: true
      verificationCode:
        description: "Stormtrooper Verification Code"
        required: true
      ghuser:
        description: "GitHub Username"
        required: true
      userid:
        description: "GitHub UserID"
        required: true
jobs:
  verify:
    name: Stormtrooper Verification
    runs-on: ubuntu-latest
    steps:
      - name: Check fork
        if: github.event.repository.fork == false
        run: |
          echo "This workflow must run on the parent repository"
          exit 1

      - name: Mask Input
        id: add_mask
        run: |
          VERIFICATION_CODE=$(jq -r '.inputs.verificationCode' $GITHUB_EVENT_PATH)
          echo ::add-mask::$VERIFICATION_CODE
          echo SECRET_CODE="$VERIFICATION_CODE" >> $GITHUB_ENV

      - name: Find Pull Request
        uses: juliangruber/find-pull-request-action@v1
        id: find-pull-request
        with:
          author: ${{ inputs.ghuser }}

      - name: Checkout
        if: steps.find-pull-request.outputs.number > 0
        uses: actions/checkout@v3

      - name: Add PR Comment
        if: ${{ startsWith(steps.verify-script.outputs.result, 'ERROR') }} || ${{ startsWith(steps.verify-script.outputs.result, 'SUCCESS') }}
        uses: mshick/add-pr-comment@v2
        with:
          message: kissakala
          issue: ${{ steps.find-pull-request.outputs.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Recruit to List
        if: ${{ startsWith(steps.verify-script.outputs.result, 'SUCCESS') }}
        uses: test-room-7/action-update-file@v1
        with:
          file-path: README.md
          commit-msg: New Recruit - ${{ inputs.username }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Process New Recruit
        if: ${{ startsWith(steps.verify-script.outputs.result, 'SUCCESS') }}
        uses: fjogeleit/http-request-action@v1
        with:
          url: "${{ secrets.ORG_URL }}"
          method: "POST"
          customHeaders: '{"Accept": "application/vnd.github+json", "Authorization": "Bearer ${{ secrets.ORG_TOKEN }}", "X-GitHub-Api-Version":"2022-11-28"}'
          data: '{"invitee_id":${{ inputs.userid }},"role":"direct_member"}'

      - name: Close PR
        if: ${{ startsWith(steps.verify-script.outputs.result, 'SUCCESS') }}
        uses: peter-evans/close-pull@v2
        with:
          pull-request-number: ${{ steps.find-pull-request.outputs.number }}
          comment: "Welcome to the Dark Side, stand by for further instructions."
